# Generated by Django 3.2.13 on 2022-06-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_imagemodel_gray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='gray',
            new_name='lr',
        ),
    ]
