# Generated by Django 3.2.13 on 2022-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_rename_gray_imagemodel_lr'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='bb',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
    ]
