# Generated by Django 3.2.13 on 2022-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0005_imagemodel_bb'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='fore',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
    ]
