# Generated by Django 3.2.13 on 2022-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0006_imagemodel_fore'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='re_estimate',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
    ]
