# Generated by Django 3.2.13 on 2022-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0008_auto_20220714_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='corner',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
    ]
