# Generated by Django 3.2.13 on 2022-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0011_alter_imagemodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='bb',
            field=models.ImageField(default='img_bb.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='corner',
            field=models.ImageField(default='img_corner.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='fore',
            field=models.ImageField(default='img_fore.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='lr',
            field=models.ImageField(default='img_lr.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='new_corner',
            field=models.ImageField(default='img_new_corner.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='new_lr',
            field=models.ImageField(default='img_new_lr.png', upload_to=''),
        ),
    ]
