# Generated by Django 3.2.13 on 2022-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0013_alter_imagemodel_corner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='new_corner',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='corner_old',
            field=models.ImageField(default='img_corner_old.png', upload_to=''),
        ),
    ]
