# Generated by Django 3.2.13 on 2022-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0014_auto_20220724_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='new_lr',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='lr_old',
            field=models.ImageField(default='img_lr_old.png', upload_to=''),
        ),
    ]
