# Generated by Django 3.2.13 on 2022-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0015_auto_20220724_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='lr_old',
            field=models.ImageField(default='img_lr_old__.png', upload_to=''),
        ),
    ]
