# Generated by Django 3.2.13 on 2022-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0016_alter_imagemodel_lr_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='lr_old',
            field=models.ImageField(default='img_lr_old.png', upload_to=''),
        ),
    ]
